### ISSUE TITLE
.local-chromium folder gets created but doesn't get deleted

### ISSUE THREAD

**Issue by KyroOW** [Decimation/SmartImage#25] opened 2022-06-28 10:52 UTC
Every time i search an image in a folder, a .local-chromium folder will be created in the same folder and does not get deleted once the search is complete.

If SmartImage needs chromium to work, it should create those files where the .exe is located so it could re-use them and wouldn't have to re-create the same files in every folder i search an image into.

Maybe they actually get deleted once the search is done but there is a bug because those are onedrive folders or something, still, it would be better if the solution above was applied because otherwise it's a big waste of resource and time.

https://i.imgur.com/SJzuc5z.png
https://i.imgur.com/pEAruvS.png
https://i.imgur.com/gk3dLHl.png

**Comment by Decimation** [comment] 2022-06-28 11:15
Yes, I've noticed this issue and I plan on resolving it in the next version. I'll aim on releasing it today if possible.

**Comment by Decimation** [comment] 2022-06-28 18:28
I've been working on a fix, and I think this [https://github.com/hardkoded/puppeteer-sharp/issues/1909#issue-1133282433](issue) with Puppeteer-Sharp is likely the cause. I'm trying to create a workaround.

**Closed** 2022-10-31 20:46 UTC
Labels: bug
